### ISSUE TITLE
humann2 metaphlan2 database download issue

### ISSUE THREAD

**Issue by srikanthkris** [biobakery/humann#10]
Hi,

I am using Humann2 . Our servers don't have access to dropbox. 

So i have downloaded metaphlan2 database and have indexed them with bowtie2.

I have already classified my samples using metaphlan without any issue. Now to functionally classify i am trying to use Humann2

the following is my code 

humann2 --input *.fa --metaphlan path_to_metaphlan2/ --output path_to_output --nucleotide-database chocophlan --protein-database uniref --threads 16

my problem is metaphlan2.py tries to download database from dropbox and endsup failing. 

when i used metaphlan2 previously i was able to overcome this using the --index option 

Can you please let me know if there is a way to override the default download option.

I have attached the error message for ur perusal

Thank you
-Kris
[metaphlan_error.txt](https://github.com/biobakery/humann/files/4916192/metaphlan_error.txt)

**Comment by ljmciver** [comment]
Hi Kris - You can run metaphlan2 first and provide that input to humann2. It sounds like if you add the --index option to the metaphlan2 run that should resolve the download error you are seeing. Then run humann with the option `--taxonomic-profile <file>` and it will not rerun metaphlan2. I am going to close this ticket as I think this plan should resolve your error. Please post if you continue to have errors!

Thank you,
Lauren
