### ISSUE TITLE
Counter download

### ISSUE THREAD

**Issue by fbeghini** [biobakery/humann#2]
HUMAnN when installed still tries to download the counter file from bitbucket

https://github.com/biobakery/humann/blob/350638d542cc7d56c0ce1094d4c60edb9eee3a62/setup.py#L552

**Comment by fconstancias** [comment]
Hi @fbeghini,

I can confirm that humann is trying to download 'mpa_v30_CHOCOPhlAn_201901.tar' database when running and providing the metaphlan database as an option do not fix the issue - see below.
Do you have any idea how to fix this?

Thanks


```
(humann3a) $ humann \
> --input $INPUT$NAME"_DNA_cat.fastq.gz" \
> --output $OUT \
> --memory-use maximum \
> --threads $NSLOTS \
> --protein-database /datadrive05/Flo/db/humann3/uniref \
> --search-mode uniref90 \
> --bowtie-options '--bowtie2db /home/constancias/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901' \
> --output-format tsv 
Output files will be written to: /datadrive05/Flo/Saliva/Saliva2/humann3_DNA
Decompressing gzipped file ...



Running metaphlan ........

CRITICAL ERROR: Error executing: /home/constancias/miniconda3/envs/humann3a/bin/metaphlan /datadrive05/Flo/Saliva/Saliva2/humann3_DNA/MP9_SUB_DNA_cat_humann_temp/tmp4m20bs1a/tmplf_4y_mq -t rel_ab -o /datadrive05/Flo/Saliva/Saliva2/humann3_DNA/MP9_SUB_DNA_cat_humann_temp/MP9_SUB_DNA_cat_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /datadrive05/Flo/Saliva/Saliva2/humann3_DNA/MP9_SUB_DNA_cat_humann_temp/MP9_SUB_DNA_cat_metaphlan_bowtie2.txt --nproc 18

Error message returned from metaphlan :

Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

File /home/constancias/miniconda3/envs/humann3a/lib/python3.7/site-packages/metaphlan/metaphlan_databases/file_list.txt already present!
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/humann3a/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/constancias/miniconda3/envs/humann3a/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/home/constancias/miniconda3/envs/humann3a/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/home/constancias/miniconda3/envs/humann3a/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v30_CHOCOPhlAn_201901.tar'

```

**Comment by fbeghini** [comment]
Hi @fconstancias, can you check which MetaPhlAn build is installed in the humann3a environment?

**Comment by fconstancias** [comment]
```
(humann3a) $ metaphlan --version
```

> MetaPhlAn version 3.0 (25 Feb 2020)

**Comment by fbeghini** [comment]
Okay, it installed an older build. You should try to update the metaphlan package and check if the installed version is `3.0.1 (25 Jun 2020)`

**Comment by fconstancias** [comment]
I have updated metaphlan:

`(humann3a) $metaphlan --version`

> MetaPhlAn version 3.0.1 (25 Jun 2020)

But now there is a issue with bowtie2:

`(humann3a) $humann --input $INPUT$NAME"_DNA_cat.fastq.gz" --output $OUT --memory-use maximum --threads $NSLOTS --protein-database /datadrive05/Flo/db/humann3/uniref --search-mode uniref90`

> Output files will be written to: /datadrive05/Flo/Saliva/Saliva2/humann3_DNA
> Decompressing gzipped file ...
> 
> CRITICAL ERROR: Can not call software version for bowtie2
> 

`(humann3a) $ bowtie2 --version`
> /home/constancias/miniconda3/envs/humann3a/bin/bowtie2-align-s version 
> 64-bit
> Built on 
> Sat Jun  6 20:17:22 UTC 2020
> Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.123_1667d2b) 
> Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/constancias/miniconda3/envs/humann3a/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1591474367590/work=/usr/local/src/conda/bowtie2-2.4.1 -fdebug-prefix-map=/home/constancias/miniconda3/envs/humann3a=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
> Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
>

**Comment by fbeghini** [comment]
Yes, the latest bowtie2 version available on conda has `--version` broken.
The latest humann package (3.0.0.alpha.3) has removed the check for the bowtie2 version, a warning is thrown, instead.

((https://forum.biobakery.org/t/humann-3-cannot-call-bowtie2-version/576/13))

**Comment by fconstancias** [comment]
Thanks. downgrading bowtie2 solved the issue.
`conda install -c bioconda bowtie2=2.3.5.1`
