### ISSUE TITLE
Cannnot download databases

### ISSUE THREAD

**Issue by Lix1993** [biobakery/humann#25]
CRITICAL ERROR: Unable to download and extract from URL: http://huttenhower.sph.harvard.edu/humann_data/chocophlan/full_chocophlan.v296_201901.tar.gz

**Comment by Lix1993** [comment]
It seems [http://huttenhower.sph.harvard.edu/humann_data/](http://huttenhower.sph.harvard.edu/humann_data/) no longer exists

**Comment by patrick-douglas** [comment]
> CRITICAL ERROR: Unable to download and extract from URL: http://huttenhower.sph.harvard.edu/humann_data/chocophlan/full_chocophlan.v296_201901.tar.gz

Dear Lix1993
I had the same issue and I've found the file [here ](http://cmprod1.cibio.unitn.it/databases/HUMAnN/). 
You can just change your scripts with the updated link, but I suggest you download it and keep it offline just in case.

I hope it helps

All best 
Patrick~
