### ISSUE TITLE
KEGG database

### ISSUE THREAD

**Issue by Fedorov113** [biobakery/humann#4]
Hello! 
First of all, I am using code from branch `2.9`, since the newer metaphlan output is not compatible with older Humann2 versions. 

I have prepared all the necessary files from newer licensed KEGG database, and followed the instructions on preparing custom database, which all worked as expected. However, when I try to run humann2 `humann2 --input $SAMPLE.fastq --output $OUTPUT_DIR --id-mapping legacy_kegg_idmapping.tsv --pathways-database humann1/data/keggc --protein-database custom_database --bypass-nucleotide-search` it says `CRITICAL ERROR: The directory provided for the translated database contains files ( genes.filtered.dmnd ) that are not of the expected version. Please install the latest version of the database: 201901`. 

I can see that the code checks for Chocophlan db version in `protein_database` file name, which makes custom databases useless. Can I just add this string to database name, or will I have other issues down the road? Do you have plans on supporting KEGG database further?

Thank you!

**Comment by Fedorov113** [comment]
Well, yes, adding `201901` to database filenames works. just fine.

**Comment by ljmciver** [comment]
Hi @Fedorov113 , Thanks for the post! Yes we have to check for the 201901 in the database name to make sure the user is running with the correct version of the databases that are in sync with the code version. You are right if you add this naming scheme to your custom database it should work ok. Sorry for the confusion.

Thanks,
Lauren
