### ISSUE TITLE
ERROR：using fastq file as input when running humann2 

### ISSUE THREAD

**Issue by hyystvar** [biobakery/humann#5]
When I use fastq as input file to runningHUMANN2, it returned "Enter password for  in Bitbucket.org HTTP at bitbucket.org". What should I do?
The HUMANN2 is installed by conda.

**Comment by ljmciver** [comment]
Hi @hyystvar , Thanks for the post! Sorry you are currently seeing this error. I think if you install the latest version of HUMAnN v2 it should resolve this error. I think it might have been related to an old counter we were using in bitbucket to track pypi downloads before pypi setup tracking with their new UI.

Thanks,
Lauren
