### ISSUE TITLE
which release of uniref was used?

### ISSUE THREAD

**Issue by nick-youngblut** [biobakery/humann#6]
I believe that one can only download diamond databases for uniref50 or uniref90 and not the fasta of all sequences. One could obtain the sequences from the uniprot ftp site (ftp://ftp.uniprot.org/pub/databases/uniprot/previous_releases/), but which uniref release was used to create the diamond databases? The [humann2 paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6235447/) doesn't seem to include that information, and I don't see it in the manual. Can you please provide info on which uniref release was used?

**Comment by franzosa** [comment]
Please see https://forum.biobakery.org/t/uniref90-and-metacyc-database-versions-and-dates/458/ and direct follow-up questions there. Thanks.
