### ISSUE TITLE
humann3: cannot set temporary directory 

### ISSUE THREAD

**Issue by nick-youngblut** [biobakery/humann#7]
It appears that the user cannot directly set the temporary directory. Instead it's set based on the user-provided basename: `config.temp_dir=os.path.join(output_dir,config.file_basename+"_humann_temp")`. For some use-cases, it would be helpful to be able to specifically set the temporary file directory.

**Comment by ljmciver** [comment]
Hi @nick-youngblut , Thanks for the post! Yes, sorry a user can't set the tmp folder directly but if you change the location of the output folder it will also change the location of the tmp folder. 

Thanks,
Lauren

**Comment by nick-youngblut** [comment]
So this feature will never be implemented? It might be helpful for others that later search for this feature if you put a label on this issue of "will no implement", as done for snakemake and other github repos.

**Comment by nick-youngblut** [comment]
Would you accept a pull request if I were to implement the code changes? If yes, it would be helpful to know why you haven't merged this PR: https://github.com/biobakery/humann/pull/3https://github.com/biobakery/humann/pull/3 and if you will merge it anytime soon.

**Comment by ljmciver** [comment]
Hi @nick-youngblut - Pull #3 was one I created just for informative purposes to allow us to easily see what changed between the two major versions (we ended up renaming v2.9 to v3) before we reformatted/renamed the python package (which with the file moves will make a quick view of the changes a bit harder to get to). When we are ready to fully release the v3 we will be merging a different branch.

Sorry if I was confused on your temp folder request. The code uses the temp folder to allow for the resume mode so if we moved the temp folder to another location I worry it might make the resume mode a bit more confusing for users. Also the temp files can be really large so I would not suggest pointing the temp folder to a location like tmp but instead placing it in the same location as the output folder where the user has a bit of space. Is there a specific use case you have where the tmp folder in the output folder is an issue? Please let me know and we can figure something out.

Thanks,
Lauren

**Comment by nick-youngblut** [comment]
Thanks for the clarification on the PR!

For large scale analyses (eg., running humann in parallel on 100's of samples), read/write becomes a huge bottleneck. By allowing the user to specify the temp directory, the user can then use a location that can alleviate I/O congestion (eg,. by using shared memory or an SSD file system). The user could just use such "fast" read/write locations for the output directory and then copy over their files to the final "slow" read/write location, but this adds needless extra compute versus separating the locations for temp files versus the final output files. 

I don't understand the resume mode issue. If the user originally specified the temp directory for the first run, then they can easily provide it for the "resume" run.

**Comment by ljmciver** [comment]
Hi @nick-youngblut , The resume mode allows a user to just rerun the remaining steps if needed. So say for example a user wants to just run the nucleotide search and get results and then run again to get the results plus the translated search. With the resume option the user would not have to rerun the nucleotide search again in the second run. It is useful to have this feature to save a bit of compute! 

Yes, I totally see your point about the fast I/O space. We have a scratch option implemented in our workflows so that we can use two folders for our I/O. We will add this to our list and consider the tmp folder option for a future release.

Thanks,
Lauren

**Comment by nick-youngblut** [comment]
Great! Thanks (in advance) for making the change!

**Comment by novitch** [comment]
Hi, 
I didn't expected a specific discussion about this point but it was exactly what I wanted to know. Let us know if you plan to make this option !
